import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

/**
 * The API reference, generated by `scripts/api-docs.mjs` (TypeDoc +
 * typedoc-plugin-markdown) into `.generated/api`. Each Markdown file is one
 * page; its id is its path, e.g. `index` or `core/index`.
 */
const api = defineCollection({
  loader: glob({
    pattern: '**/*.md',
    base: './.generated/api',
    generateId: ({ entry }) => entry.replace(/\.md$/, ''),
  }),
  schema: z.object({
    title: z.string(),
    navTitle: z.string(),
    description: z.string(),
    module: z.string(),
    route: z.string(),
    order: z.number(),
  }),
});

export const collections = { api };
